"""Compare Vita HUD caching/decoding against the original per-pixel renderer."""
from pathlib import Path
import os
import subprocess
import tempfile
root = Path(__file__).resolve().parents[2]
source = (root / "raverace/src/rr_gxm.c").read_text()
start = source.index("static bool build_text(")
end = source.index("/* Compare cached pixels", start)
function = source[start:end].replace("build_text(", "optimized_text(").replace("txt_rgba", "optimized").replace("frame_mem.", "g_rr.")
reference = '#include <stdint.h>\n#include <stdbool.h>\n#include <stdio.h>\n#include <stdlib.h>\n#include <string.h>\n#define NW 640\n#define NH 480\nstatic struct { uint8_t tilemapattr[4], text[8192], cgram[0x1e000], pal[0x18000]; } g_rr;\nstatic uint8_t gamma_prom[3][256];\nstatic void pen_rgb(int pen,uint8_t *o){pen&=0x7fff;for(int c=0;c<3;c++)o[c]=gamma_prom[c][g_rr.pal[pen+c*0x8000]];}\nstatic _Alignas(4) uint8_t original[NW*NH*4], optimized[NW*NH*4];\nstatic bool reference(int text_palbase) {\n    const uint16_t a0 = (uint16_t)(g_rr.tilemapattr[0] << 8 | g_rr.tilemapattr[1]);\n    const uint16_t a1 = (uint16_t)(g_rr.tilemapattr[2] << 8 | g_rr.tilemapattr[3]);\n    const int sx = (a0 - 0x35c) & 0x3ff, sy = a1 & 0x3ff;\n    bool any = false;\n\n    for (int y = 0; y < NH; y++) {\n        const int ty = (y + sy) & 0x3ff, trow = ty >> 4, cy = ty & 15;\n        uint8_t *d = original + (size_t)y * NW * 4;\n        for (int x = 0; x < NW; x++, d += 4) {\n            d[3] = 0;\n            const int tx = (x + sx) & 0x3ff;\n            const int ti = (trow * 64 + (tx >> 4)) * 2;\n            const uint16_t w = (uint16_t)(g_rr.text[ti] << 8 | g_rr.text[ti + 1]);\n            const int code = w & 0x3ff;\n            int cx = tx & 15;\n            if (w & 0x400) cx = 15 - cx;\n            const int ccy = (w & 0x800) ? 15 - cy : cy;\n            const uint32_t off = (uint32_t)code * 128 + (uint32_t)ccy * 8 + (uint32_t)(cx >> 1);\n            const uint8_t byte = off < 0x1e000 ? g_rr.cgram[off] : g_rr.text[off - 0x1e000];\n            const int pix = (cx & 1) ? (byte & 0xf) : (byte >> 4);\n            if (pix == 0xf) continue;\n            const uint8_t p8 = (uint8_t)((w >> 12) << 4 | pix);\n            pen_rgb(text_palbase + p8, d);\n            d[3] = 0xff;\n            any = true;\n        }\n    }\n    return any;\n}\n\n'
test = 'int main(void){\n srand(22);\n for(int trial=0;trial<64;trial++){\n  uint8_t *p=(uint8_t*)&g_rr; for(size_t i=0;i<sizeof g_rr;i++)p[i]=rand();\n  for(int c=0;c<3;c++)for(int i=0;i<256;i++)gamma_prom[c][i]=rand();\n  if(trial==0) {memset(g_rr.cgram,255,sizeof g_rr.cgram);memset(g_rr.text,255,sizeof g_rr.text);}\n  int pal=(rand()&127)*256;\n  for(int mutation=0;mutation<7;mutation++) {\n   if(mutation==1)g_rr.tilemapattr[0]++;\n   if(mutation==2)g_rr.text[0]^=0x80;\n   if(mutation==3)g_rr.cgram[0]^=0xff;\n   if(mutation==4)g_rr.pal[pal]^=0xff;\n   if(mutation==5)pal=(pal+256)&0x7fff;\n   if(mutation==6)memset(g_rr.cgram,0xff,sizeof g_rr.cgram);\n   if(reference(pal)!=optimized_text(pal))return 1;\n   if (!txt_pixels_changed) return 3;\n   bool cached=optimized_text(pal);\n   if (txt_pixels_changed || cached != reference(pal)) return 4;\n   for(int i=0;i<NW*NH;i++){\n    if(original[i*4+3]!=optimized[i*4+3] || (original[i*4+3] && memcmp(original+i*4,optimized+i*4,3))) {fprintf(stderr,"mismatch %d %d\\n",trial,i);return 2;}\n   }\n  }\n }\n puts("PASS: 448 HUD frames and cache invalidations match original; unchanged frames reuse pixels");\n}\n'
with tempfile.TemporaryDirectory(prefix="rr-hud-") as d:
    src = Path(d) / "hud.c"
    binary = Path(d) / "hud"
    src.write_text(reference + "static bool txt_pixels_changed;\n" + function + test)
    subprocess.run(["cc", "-O2", "-fsanitize=address,undefined", str(src), "-o", str(binary)], check=True)
    subprocess.run([str(binary)], check=True, env={**os.environ, "UBSAN_OPTIONS": "halt_on_error=1"})
